#This was a big help: https://github.com/jdblischak/smk-simple-slurm/blob/main/simple/config.v8%2B.yaml#L5
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p slurmLogs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=slurmLogs/{rule}/{rule}-{wildcards}-%x.%j.log
    --error=slurmLogs/{rule}/{rule}-{wildcards}-%x.%j.log
    --mail-user=aaron.yerke@usda.gov
    --mail-type=BEGIN,END,FAIL
    --parsable
default-resources:
  - partition=short
  - mem_mb=1000
  - time=120 #num minutes
  - nodes=10
  - ntasks=5
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True